### ISSUE TITLE
Makefile bails out on CentOS 8

### ISSUE THREAD

**Issue by shakeyourbunny** [pukkandan/yt-dlc#4]
## Checklist

- [ ] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dlc version **2020.10.31**
- [x] I've checked that all provided URLs are alive and playable in a browser (not relevant in this case)
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped (not relevant in this case)
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
$ make
mkdir -p zip
for d in youtube_dlc youtube_dlc/downloader youtube_dlc/extractor youtube_dlc/postprocessor ; do \
  mkdir -p zip/$d ;\
  cp -pPR $d/*.py zip/$d/ ;\
done
touch -t 200001010101 zip/youtube_dlc/*.py zip/youtube_dlc/*/*.py
mv zip/youtube_dlc/__main__.py zip/
cd zip ; zip -q ../youtube-dlc youtube_dlc/*.py youtube_dlc/*/*.py __main__.py
rm -rf zip
echo '#!/usr/bin/env python' > youtube-dlc
cat youtube-dlc.zip >> youtube-dlc
rm youtube-dlc.zip
chmod a+x youtube-dlc
COLUMNS=80 /usr/bin/env python youtube_dlc/__main__.py --help | /usr/bin/env python devscripts/make_readme.py
/usr/bin/env: /usr/bin/env: ‘python’‘python’: No such file or directory: No such file or directory

make: *** [Makefile:76: README.md] Error 127

$ which python
/usr/bin/which: no python in (/home/pulaski/bin:/home/pulaski/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
$ which python3
/usr/bin/python3

```

## Description

Makefile assumes that there is a "python" executable in the system path which it will not find in the RedHat family of Linux (CentOS, SciLinux, Fedora, RedHat, ...)

Reason is that they do not ship Python with it, at least not out of scope of system use. You have to explicitely install Python (default is Python 3) for using it, what I did.

But you don't get a "python" executable, the Makefile (and the main script itself) should explicitely state, that it uses Python 3.

**Comment by shakeyourbunny** [comment]
After replacing "/usr/bin/env python" with "/usr/bin/env python3" the Makefile still does not run through (because pandoc is not installed). There seems to be a check for it, but it has a typo.

``
$ make
COLUMNS=80 /usr/bin/env python3 youtube_dlc/__main__.py --help | /usr/bin/env python3 devscripts/make_readme.py
/usr/bin/env python3 devscripts/make_contributing.py README.md CONTRIBUTING.md
/bin/sh: pandoc: command not found
/bin/sh: line 0: [: =: unary operator expected
pandoc -f markdown -t plain README.md -o README.txt
make: pandoc: Command not found
make: *** [Makefile:92: README.txt] Error 127
``

**Comment by pukkandan** [comment]
`make` is equivalent to `make all` which also generates all the necessary documentation. `pandoc` is essential for it. Try using `make youtube-dlc` to build only the core program

**Comment by shakeyourbunny** [comment]
Yes, it builds, after I modified the makefile a bit (except documentation).

Is there a reason, that if I do

````
$ youtube-dl --help
````
does not the options for the sponskrub stuff (the --format-sort stuff is present)? Sorry, that I'm pedantic.

**Comment by pukkandan** [comment]
Update your source to the current master or release, it should show. 
It was broken yesterday, but I fixed it when making the release

**Comment by pukkandan** [comment]
@shakeyourbunny Did updating fix your issue?

**Comment by pukkandan** [comment]
I am closing this since there has been no response
